//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Customers = new HashSet<Customer>();
            this.Manegers = new HashSet<Maneger>();
        }

        [Required(ErrorMessage = "Mã đăng ký là bắt buộc...")]
        [Display(Name = "Mã đăng kí")]
        public int IDAccount { get; set; }

        [Required(ErrorMessage = "Tên không được để trống...")]
        [Display(Name = "Tên đăng nhập")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Mật khẩu không được để trống...")]
        [DataType(DataType.Password)]
        [Display(Name = "Mật khẩu:")]
        public string Password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Mật khẩu không trùng khớp...")]
        [Compare("Password")]
        [DisplayName("Nhập lại mật khẩu")]
        public string ConfirmPassword { get; set; }
        public string Role { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maneger> Manegers { get; set; }
    }
}
